### ISSUE TITLE
KeyError: '11.8'

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-isonet#4]
after updating the plugin with scipion 3.3.0 i got the following error starting 'scipion3 plugins':
$ scipion3 plugins
Scipion v3.3.0 - Eugenius
Error retrieving plugin IsoNET binaries:  '11.8'
Error retrieving plugin scipion-em-isonet binaries:  '11.8'
Couldn't get binaries definition of scipion-em-isonet plugin: '11.8'
Traceback (most recent call last):
  File "/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/miniconda/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 334, in getInstallenv
    plugin.defineBinaries(env)
  File "/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/devel/scipion-em-isonet/isonet/__init__.py", line 135, in defineBinaries
    cls.addIsonetPackage(env)
  File "/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/devel/scipion-em-isonet/isonet/__init__.py", line 96, in addIsonetPackage
    cudalib = utils.CudaLibs().getCudaLibraries(cudaVersion)
  File "/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/devel/scipion-em-isonet/isonet/utils.py", line 49, in getCudaLibraries
    matches = self.cudaTable[str(cudaVersion)]
KeyError: '11.8'

adding the following line removed this error message:
$ git diff isonet/utils.py
diff --git a/isonet/utils.py b/isonet/utils.py
index 75fe90b..e9337aa 100644
--- a/isonet/utils.py
+++ b/isonet/utils.py
@@ -23,6 +23,7 @@ class CudaLibs:
         self.cudaTable['11.2'] = [('tensorflow==2.5.0', 'cudnn=8.1', 'gcc=7.3.1', 'numpy==1.19.5', 'python=3.7')]
         self.cudaTable['11.4'] = self.cudaTable['11.2']
         self.cudaTable['11.6'] = self.cudaTable['11.2']
+        self.cudaTable['11.8'] = self.cudaTable['11.2']
 
     def runShell(self, cmd, allow_non_zero=False, stderr=None):
         if stderr is None:

**Comment by fonsecareyna82** [comment]
New release fix this problem
