### ISSUE TITLE
Error in subtomogram extraction

### ISSUE THREAD

**Issue by rdrighetto** [scipion-em/scipion-em-isonet#8]
The protocol gives the following error at the subtomogram extraction step:

```
######Isonet starts extracting subtomograms######

02-28 14:52:38, WARNING  [isonet.py:295] subtomo directory exists, the current directory will be overwritten
Extract from origional tomogram /scicore/home/engel0006/GROUP/ScipionUserData/diogori/projects/Tutorial_20240227/Runs/002583_ProtIsoNetTomoReconstruction/extra/tomograms/TS_17072022_BrnoKrios_Arctis_p3ar_grid_Position_112.mrc
02-28 14:52:43, ERROR    [isonet.py:314] Traceback (most recent call last):
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/isonet-0.2.1/IsoNet/bin/isonet.py", line 307, in extract
    extract_subtomos(d_args)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/isonet-0.2.1/IsoNet/preprocessing/prepare.py", line 53, in extract_subtomos
    seeds=create_cube_seeds(orig_data, it.rlnNumberSubtomo, settings.crop_size,mask=mask_data)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/isonet-0.2.1/IsoNet/preprocessing/cubes.py", line 18, in create_cube_seeds
    sample_inds = np.random.choice(len(valid_inds[0]), nCubesPerImg, replace=len(valid_inds[0]) < nCubesPerImg)
  File "mtrand.pyx", line 902, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
[run.stdout.txt](https://github.com/scipion-em/scipion-em-isonet/files/14435016/run.stdout.txt)

```

I have tried several different sizes of subtomograms, including the defaults. Please find the full log attached:
[run.stdout.txt](https://github.com/scipion-em/scipion-em-isonet/files/14435022/run.stdout.txt)

**Comment by rdrighetto** [comment]
This error was caused by me giving wrong parameters for the mask generation, i.e. it was trying to extract particles from an empty tomogram.
